language: ruby
rvm:
 - 2.5.8
 - 2.6.6
 - 2.7.1
gemfile:
 - gemfiles/activerecord_5_2.gemfile
 - gemfiles/activerecord_6_0.gemfile
 - gemfiles/activerecord_6_1.gemfile
services:
 - postgresql
before_script:
 - psql -c 'create database postgres_vacuum_monitor_test;' -U postgres
addons:
  postgresql: '9.6'
