language: ruby
rvm:
 - 2.5.6
 - 2.6.3
gemfile:
 - gemfiles/activerecord_5.gemfile
 - gemfiles/activerecord_6.gemfile
services:
 - postgresql
before_script:
 - psql -c 'create database postgres_vacuum_monitor_test;' -U postgres
addons:
  postgresql: '9.6'
